swagger: '2.0'
info:
  title: Site provider api
  version: "unsupported"
  description: |
    ![Logo](https://scdn.ntgm.rocks/image/OTH/200/auto/igp-logo-dark.png)

    # Out of support

    ### **This API documentation is no longer supported. Please contact your iGP account manager or project manager to provide you with a new URL for documentation**

paths: {}